services:
  node:
    build:
      context: ./services/node
      args:
        USER_NAME: ${USER_NAME:-www-data}
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - ${APP_FOLDER}:/app
      - ${SSH_AUTH_SOCK}:/ssh-agent
